### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by zplusfour** [sugarfi/wispkoe-api#1]
hey sugarfi
wassup

i created a pull request on wispoke's github repo... can you tell the author (if you know him) to check the pull requests?
its kind of an important pull request, because it will change some important things (i guess):
- Since the new version of express was released, you can now use `express.urlencoded` or `express.json` or any other methods, instead of using `bodyParser`
- the code looks untidy, so i formatted it using prettier

thank you :)

**Comment by sugarfi** [comment]
will do

**Comment by zplusfour** [comment]
thank you :D
